### ISSUE TITLE
Add setting for felling time

### ISSUE THREAD

**Issue by depascalis** [fluxionary/minetest-choppy#2]
I don't know if this is a bug, but it takes imo a very long time before a tree has been felled. Maybe add a setting for how long this should take. As a creative user I'd prefer it to be instantly, but I understand that that isn't preferable for other game modes.

**Comment by fluxionary** [comment]
currently the felling time scales to the power of the axe. i could add a parameter to speed it up (or slow it down) by some %, if that'd work for you.

**Comment by fluxionary** [comment]
i've added a dig speed multiplier parameter: https://github.com/fluxionary/minetest-choppy/commit/f8261cf2e848639b40a5abc6f9549e27363b1d45
