### ISSUE TITLE
hud & chat texts

### ISSUE THREAD

**Issue by blaboing** [fluxionary/minetest-choppy#6]
/toggle_choppy tells you "press sneak to enable choppy"
I would change it to "press & hold sneak to enable choppy"

The HUD always displays "chopping @1\npress SNEAK to stop" no matter which mode you use.
It should be "chopping @1\nrelease SNEAK to stop" for sneak mode

**Comment by fluxionary** [comment]
thanks, fixed :)

**Comment by blaboing** [comment]
Did you maybe miss the first part?

> /toggle_choppy tells you "press sneak to enable choppy"
> I would change it to "press & hold sneak to enable choppy"

https://github.com/fluxionary/minetest-choppy/blob/3f41d6109015074c5a6195e70bfbcf6edc9f411f/commands.lua#L8

**Comment by fluxionary** [comment]
> Did you maybe miss the first part?

whoops! got it now i think

**Comment by blaboing** [comment]
mh nope lol
now you changed the text for both modes.
sneak hold mode "press & hold sneak to enable choppy"
sneak stop mode "press sneak to disable choppy"

**Comment by fluxionary** [comment]
> mh nope lol now you changed the text for both modes. sneak hold mode "press & hold sneak to enable choppy" sneak stop mode "press sneak to disable choppy"

i've changed both to "press and hold", as that's probably the most clear
