### ISSUE TITLE
Tree nodes on top of tree

### ISSUE THREAD

**Issue by UnchainedDevelopment** [fluxionary/minetest-choppy#9]
When using choppy I have noticed that every now and then even if I have inventory space I will find the trunk nodes on top of the trees. I believe reversing the cutting action from bottom to top could assist in this.

**Comment by fluxionary** [comment]
> When using choppy I have noticed that every now and then even if I have inventory space I will find the trunk nodes on top of the trees. I believe reversing the cutting action from bottom to top could assist in this.

sorry i haven't replied before, haven't been feeling well.

the top-to-bottom behavior is very much a necessary improvement over other tree-cutting mods. however, i use pre-programmed estimates of the maximum size of a tree, and i know i got that wrong at least once. if you let me know which tree(s) are leaving behind tops, i can update those values.
